services:
  postgres:
    image: postgres:16-alpine
    container_name: user_profile_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: radioai
      POSTGRES_USER: radioai
      POSTGRES_PASSWORD: radioaipassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: user_profile_api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_ENV: development
      APP_PORT: 8080

      DB_DSN: host=postgres user=radioai password=radioaipassword dbname=radioai port=5432 sslmode=disable

      JWT_ACCESS_SECRET: "CHANGE_ME_ACCESS_SECRET_very_long"
      JWT_REFRESH_SECRET: "CHANGE_ME_REFRESH_SECRET_very_long"
      ACCESS_TOKEN_EXPIRES: "15m"
      REFRESH_TOKEN_EXPIRES: "720h"

      AWS_S3_BUCKET: "your-bucket-name"
      AWS_REGION: "eu-west-1"

      ADMIN_API_KEY: "CHANGE_ME_ADMIN_KEY"

      CORS_ALLOW_ORIGINS: ""
      OTEL_EXPORTER_OTLP_ENDPOINT: ""

    ports:
      - "8080:8080"

volumes:
  postgres_data:
